### ISSUE TITLE
Thoughts on the name?

### ISSUE THREAD

**Issue by Glavin001** [Unibeautify/unibeautify#1]
What do you think about `unibeautify` as the new name? This project will eventually support a Node.js API, CLI, Atom, and Sublime editor plugins.

**Comment by aidistan** [comment]
I like this name. Hope we could eventually support them all.

I'm a little curious about how we sperate beautifiers from the core of Unibeautify. And if it's clear, hope we could start to contribute to sperated beautifiers ASAP.

**Comment by Glavin001** [comment]
> I'm a little curious about how we sperate beautifiers from the core of Unibeautify. 

I'm working on a way to separate beautifier packages and allow a single beautifier repository to be used for:
- Atom packages (`apm install beautifier-${name}`)
- Node.js API library (`npm install beautifier-${name}`)
- Global CLI (`npm install beautifier-${name} --global`)

Each beautifier will be separated into individual packages and conform to a common interface. They will be published to both `npm` (Node.js) and `apm` (Atom). The naming convention will be `beautifier-${name}` (thoughts on this?) and can be installed with npm as Node.js library or as global CLI. See https://github.com/Unibeautify/unibeautify-cli/issues/4 for more details and follow my progress on this for the CLI part.

> And if it's clear, hope we could start to contribute to sperated beautifiers ASAP.

I intend to provide a sample beautifier repository. The goal being that contributors could simply fork, rename the project from `beautifier-sample` to `beautifier-${name}`, implement their beautifier in the sample beautifier file provided, and finally `npm publish` and `apm publish`. All users (both on Atom and with Node.js) will immediately be able to use this beautifier!

**Comment by cocody** [comment]
beautillar ?
beautify + butterfly + caterpillar ?
input `beau` or `bea` when I want to install the `atom-Beautify` on package
