### ISSUE TITLE
Unibeautify: Adapter, Framework, or Both

### ISSUE THREAD

**Issue by bitwiseman** [Unibeautify/unibeautify#10]
Atom-beautify is not a beautifier or framework.  It is an adapter that lets users beautify JS or other languages, but depends on other tools to do the beautifying.  Those tools have no awareness of atom-beautify and can have wildly different internal design and implmentation.  Determining the cause of issues is difficult because in might be from any of several tools or from interaction with those tools. 

A beautification framework would provide facilities that other components would plug into. For example, the framework might provide a facilities to configure formatting rules and read input, establish APIs or base classes for parsed token trees, execute all requested formatting rules on those tokens, and then have one unified implementation of an output writer.  This would not support tools outside this framework, but would make it significantly easier to analyze and fix issue. 

Unibeautify can do either of these or both, but I'd make sure we've talked about it early rather than later.

**Comment by Glavin001** [comment]
See https://github.com/Unibeautify/unibeautify/issues/8#issuecomment-310282589

**Comment by Glavin001** [comment]
Unibeautify will be the adapter. @prettydiff is working on a framework over at https://github.com/Unibeautify/parse-framework
