### ISSUE TITLE
Include file extension in BeautifierBeautifyData

### ISSUE THREAD

**Issue by szeck87** [Unibeautify/unibeautify#103]
We need to use the file extension for the tmp file's postfix when creating a temp file.  For executable beautifiers that support multiple languages, there is no way to know the extension to use there with the current BeautifierBeautifyData interface.

**Comment by Glavin001** [comment]
Use `path` library + `filePath`:
- https://stackoverflow.com/a/15778396/2578205
- https://github.com/Unibeautify/unibeautify/blob/a27be0509bd8dba9e4aa84a0eb737e56cf53c527/src/beautifier.ts#L84

```javascript
const path = require('path')
const { filePath } = data; // index.html

if (filePath) {
  const extension = path.extname(data.filePath); // .html
}
```
