### ISSUE TITLE
How is Unibeautify different from Prettier?

### ISSUE THREAD

**Issue by muhajirframe** [Unibeautify/unibeautify#11]
Hi, 
I just want to know, is this projects works the same way as github.com/prettier/prettier ? Or they work differently?

**Comment by bitwiseman** [comment]
@muhajirframe 
This a good question.  The philosophy and scope of this project is still being discussed.

Off hand, I would say that prettier says it is "an opinionated code formatter", where unibeautify does not.  Also, I believe prettier is focused specifically on javascript, while unibeautify has broader aspirations.

**Comment by muhajirframe** [comment]
Nice projects.
Yeah i think so, but they also beginning to support css right now.

Looking forward for this project 👍👍👍

**Comment by Glavin001** [comment]
See https://github.com/Unibeautify/unibeautify/issues/8#issuecomment-310282589

**Comment by Glavin001** [comment]
Moving to https://github.com/Unibeautify/unibeautify.github.io/issues/34 😃 . Please subscribe there.

The answer to this question will eventually be found on the Unibeautify website: https://unibeautify.com/

Thank you for your interest!

**Comment by Glavin001** [comment]
See https://unibeautify.com/docs/about.html for details 😃. Please let me know if you have any more questions! Thank you for your interest in Unibeautify!
