### ISSUE TITLE
PHP_CodeSniffer Support

### ISSUE THREAD

**Issue by muuvmuuv** [Unibeautify/unibeautify#110]
**Beautifier Details**
Name: PHP_CodeSniffer (phpcs)
Link to project/homepage: https://github.com/squizlabs/PHP_CodeSniffer

**If this is to update an existing beautifier, please describe what should be updated**
currently, in PHP just php-cs-fixer is supported, but phpcs also supports auto fixing with the `phpcbf ` command. It would be nice to support phpcs too

Languages Supported: PHP
How is it run (node, terminal, etc): PHP terminal with `phpcs <file> <options>`

**Comment by Glavin001** [comment]
Thank you for creating this Issue, @muuvmuuv .

I've created https://github.com/Unibeautify/beautifier-php-codesniffer . Please feel free to submit a Pull Request there. I recommend following https://github.com/Unibeautify/beautifier-php-cs-fixer
Please let us know if you have any questions 😃 .

**Comment by szeck87** [comment]
This issue was moved to Unibeautify/beautifier-php-codesniffer#1
