### ISSUE TITLE
CSScomb support

### ISSUE THREAD

**Issue by muuvmuuv** [Unibeautify/unibeautify#112]
**Beautifier Details**
Name: CSScomb
Link to project/homepage: http://csscomb.com/

**If this is a new beautifier, please fill out the below**
Languages Supported: CSS, Less, Sass, SCSS
How is it run (node, terminal, etc):

Command Line:
```
csscomb assets/css
```

Node.js module:
```
var Comb = require('csscomb');
var comb = new Comb('zen');
comb.processPath('assets/css');
```

**Additional context**
provide option to use own config file in workspace root

**Comment by Glavin001** [comment]
Created https://github.com/Unibeautify/beautifier-csscomb

**Comment by szeck87** [comment]
This issue was moved to Unibeautify/beautifier-csscomb#1

**Comment by Glavin001** [comment]
Thank you @szeck87 !
