### ISSUE TITLE
Standard Options

### ISSUE THREAD

**Issue by prettydiff** [Unibeautify/unibeautify#12]
Something I have been thinking about is that options management for a long time was a mess in Pretty Diff until I rewrote the architecture of the application around a centralized standard management of options internally.  Even still options management in Atom Beautify was also kind of a mess in keeping up with various different beautifiers.

I am proposing a standard set of options with a central standard API.  A stand alone code repository under the Unibeautify organization.

## Here is what I am thinking in more detail:
* Options are defined in a central location to the Unibeautify project and not immediately associated with any particular beautifier (application agnostic).
* Options and the respective API are well documented.
* Each of the different beautifiers are free to decide which options they wish to consume/support.  A beautifier is not required to support all available options.
* New options from a beautifier should not be added unless they are integrated into the central options management first.

## Potential challenges
* We have to support the options that are already in the beautifiers and not do anything heavy handed that would break current support or backwards compatibility.
* We would have to win support from the various beautifiers.
* We would need to plan out a simple architecture that works for everybody.
* We would need living documentation that declares where the options are supported in the various beautifiers and in which IDE interfaces.

## Goals
* Simplify maintenance and management as this application covers a wide spectrum horizontally and vertically.
* Announce innovation and capabilities from various competing beautifiers in a way other beautifiers and IDE maintainers can keep up with in a compatible way.
* Provide an additional layer of logical separation of concerns for Unibeautify.

**Comment by Glavin001** [comment]
Excellent. This is exactly what I had in mind with Unibeautify.

**Comment by Glavin001** [comment]
Related to https://github.com/Unibeautify/unibeautify/issues/2

**Comment by bitwiseman** [comment]
@prettydiff  Sounds good.  Examples would be helpful in understanding what you are proposing.

**Comment by Glavin001** [comment]
In case you both have not already seen: https://github.com/Unibeautify/unibeautify/blob/master/src/options.ts#L20-L460

**Comment by Glavin001** [comment]
@prettydiff @bitwiseman : What are your thoughts on Unibeautify's current option repository and documentation? :) 

Take a look:
- https://unibeautify.github.io/docs/options.html 
- https://unibeautify.github.io/docs/beautifier-js-beautify.html
- https://unibeautify.github.io/docs/beautifier-pretty-diff.html
- https://unibeautify.github.io/docs/option-align-assignments.html
- https://unibeautify.github.io/docs/option-comma-first.html

**Comment by prettydiff** [comment]
That documentation is awesome.  I am currently working on automation all things related to options in Pretty Diff from a simple JSON list.  https://github.com/prettydiff/prettydiff/blob/3.0.0/api/options.ts#L49

The options in Pretty Diff 3 are nearly identical to the options in Pretty Diff 2, except I removed all language configuration options.  For example in Pretty Diff 2 there is an option named *jsx* for handling JSX related logic.  In Pretty Diff 3 all this is rolled into a single option named *lang*.

**Comment by Glavin001** [comment]
Thanks, @prettydiff !

Closing this issue as we are moving forward with the plan to be the standard options repository. 👍
