### ISSUE TITLE
Support bash scripts

### ISSUE THREAD

**Issue by muuvmuuv** [Unibeautify/unibeautify#131]
**Language Details**
Name: bash
Extensions: sh
Type (scripting, markup, etc): scripting
Additional details: 

**Are there any existing beautifiers that can use this language?  Please list them.**

- https://arachnoid.com/python/beautify_bash_program.html
- https://github.com/bemeurer/beautysh
- https://github.com/ewiger/beautify_bash 
- https://github.com/mvdan/sh

**Additional context**

**Comment by szeck87** [comment]
https://www.npmjs.com/package/mvdan-sh

**Comment by mvdan** [comment]
Happy to help if you run into any issues with the tool :) The npm package is just the same software, but compiled to javascript.

**Comment by szeck87** [comment]
This issue was moved to Unibeautify/beautifier-shfmt#1
