### ISSUE TITLE
Any way to use this programmatically ?

### ISSUE THREAD

**Issue by Ray-Eldath** [Unibeautify/unibeautify#140]
`README.md` pointed out "See `\test` for example", but I think it's impossible to use this programmatically without any instruction...

Could I use UniBeautify programmatically? I mean, without `Unibeautify-CLI`, could I format my code with an API like `beautifier.beautify("<my code>")` ?

I **really** want this! Thx!

**Comment by Glavin001** [comment]
What do you have in mind for using Unibeautify's API?

You can absolutely use Unibeautify as a Node.js API, as this is what https://github.com/Unibeautify/unibeautify-cli and https://github.com/Unibeautify/vscode and others *already do*.

Here's a test which shows how to `beautify`: https://github.com/Unibeautify/unibeautify/blob/master/test/index.spec.ts#L25-L44
There's auto-generated documentation: https://api.unibeautify.com/

**Comment by Ray-Eldath** [comment]
Thx.

**Comment by Glavin001** [comment]
@Ray-Eldath  What do you have in mind to build using Unibeautify's API?
