### ISSUE TITLE
Change interface data to be similar across Unibeautify

### ISSUE THREAD

**Issue by szeck87** [Unibeautify/unibeautify#147]
Interfaces should have similar property names across Unibeautify.  I'm finding that is not always the case.  Example:

[LanguageQuery](https://github.com/Unibeautify/unibeautify/blob/master/src/LanguageManager.ts#L73-L98) has `name` and `extension`, yet [BeautifyData](https://github.com/Unibeautify/unibeautify/blob/master/src/beautifier.ts#L110-L147) has `languageName` and `fileExtension`.

**Comment by Glavin001** [comment]
`name` under `LanguageQuery` can be inferred as `languageName`.
However, this is not true for `BeautifyData`.

`fileExtension` may be a valid argument, however, I'm not convinced it is significant value added.

I intentionally made these interfaces different and do not see a huge value in changing them.
