### ISSUE TITLE
Image size on website

### ISSUE THREAD

**Issue by bardware** [Unibeautify/unibeautify#178]
Hi,

I just stumble over your website and see you embed logos of languages that are 400 kByte in size. That's a lot. It looks to me it's a png embedded in svg. Maybe you can resize it.
![grafik](https://user-images.githubusercontent.com/802702/45222429-db6cd400-b2b4-11e8-8e72-25d375986054.png)

**Comment by Glavin001** [comment]
Great idea! Pull requests are very welcome! Applicable files are found at https://github.com/Unibeautify/website/tree/master/website/static/img 

@szeck87 Would you be able to transfer this Issue to https://github.com/Unibeautify/website/ ? Thank you.

**Comment by szeck87** [comment]
This issue was moved to Unibeautify/website#157

**Comment by Glavin001** [comment]
Thank you, @szeck87 !
