### ISSUE TITLE
Frequency of dependency updates (Renovate)

### ISSUE THREAD

**Issue by lassik** [Unibeautify/unibeautify#186]
Can the Renovate bot be set to update dependencies less eagerly? The pull request logs are getting hard to read and Renovate causes a constant stream of trivial GitHub notifications that apparently cannot be turned off without unwatching the repo question. Since Unibeautify is divided into many small JS modules each with its own repo, the problem is multiplied for each module watched :-/

It might be a reasonable policy to update deps before pushing a new package version to npm, or on a schedule of once a month, etc. There ought not to be a need to update deps on a weekly basis.

**Comment by szeck87** [comment]
Schedule is probably what to use:  https://renovatebot.com/docs/configuration-options/#schedule.  I agree that it runs too often and clogs up Travis.  Ideally there would be a check on PR's that make sure dependencies are up to date before it is merged (there might be an app that does that, I don't know).  Otherwise once a week for renovate would be fine.

**Comment by Glavin001** [comment]
We could use branch auto-merging: https://renovatebot.com/docs/dependency-pinning/#reducing-the-noise-of-dependency-updates

**Comment by lassik** [comment]
Thanks for responding, great to hear that there are options :) Would auto-merging remove the clutter from the PR log and GitHub notifications? Currently e.g. the [log of closed PRs for Unibeautify core](https://github.com/Unibeautify/unibeautify/pulls?q=is%3Apr+is%3Aclosed) consists almost entirely of Renovate PRs, making it hard to spot the substantial ones by humans.

**Comment by Glavin001** [comment]
Yup, it would mean no more PRs and auto-merging those as branches -- bypass PR entirely. I think this is fair. I'll look into it.

**Comment by Glavin001** [comment]
After reading https://renovatebot.com/docs/dependency-pinning/#branch-automerging and https://renovatebot.com/docs/configuration-options/#automergetype I made a change.

@lassik @szeck87 I'm hoping this does the job: https://github.com/Unibeautify/unibeautify/commit/bf06439aa2cee46e3376cc61673e5e20c6cd8288

Let me know if you think it should be changed.

**Comment by lassik** [comment]
The fix seems to be working great :)

Could this be committed to [cli](https://github.com/Unibeautify/unibeautify-cli) and [clang-format](https://github.com/Unibeautify/beautifier-clang-format) too? Those are also getting a lot of updates.

**Comment by stevenzeck** [comment]
@Glavin001 make sure to update branch protections to not require PR status checks

**Comment by lassik** [comment]
> @Glavin001 make sure to update branch protections to not require PR status checks

A lot of Renovate notifications have been popping up again for the CLI and some beautifiers. Some of them say that Renovate was unable to auto-merge so it had to make a PR. Could these protections be the reason for that?

**Comment by stevenzeck** [comment]
I thought it was due to having required status checks on PR's, but it's required status checks in general. https://github.com/renovatebot/renovate/issues/1853

**Comment by Glavin001** [comment]
Extremely frustrating. Waaaay too many notifications.

@stevenzeck I'm going to start removing the protected branches -- renaming `master` to `masterr` actually, so we can move back later once GitHub and Renovate have better support. If you see some repos failing like this, feel free to do the same.

**Comment by lassik** [comment]
Thanks to both of you for the effort :)

Another option would be to add a https://renovatebot.com/docs/presets-schedule/ of e.g. weekly. I guess it would send all the notifications in one weekly batch. But maybe you'd still have to click merge on all the PRs...

**Comment by lassik** [comment]
I've been thinking it would be awesome if Renovate could roll all of the week's updates into a single Git commit / PR / CI job. Maybe it's against the philosophy of the tool (since, from one theoretical standpoint, it's "safer" to isolate dependency updates and run a separate CI job for each) but it would be a lot easier to read the Git log that way. If it updates all deps at once and the CI job passes, it should be fine to commit them in one go. But from a quick skim of their docs I didn't find such a setting.

**Comment by Glavin001** [comment]
I disabled protected branches for all of the repositories in my notifications. Looks like it's been helping a lot.

> Another option would be to add a schedule of e.g. weekly

I actually like it being ASAP because I also use Renovate to update @unibeautify packages depending on other @unibeautify packages, like VSCode extension depends on beautifiers or even Unibeautify core itself.

> I've been thinking it would be awesome if Renovate could roll all of the week's updates into a single Git commit / PR / CI job. Maybe it's against the philosophy of the tool (since, from one theoretical standpoint, it's "safer" to isolate dependency updates and run a separate CI job for each) but it would be a lot easier to read the Git log that way.

Yeah bulk updating is against what Renovate is trying to accomplish and would also be a nightmare for myself as a reviewer -- when the update does fail, which dependency is it?

I'm happy with this PR-less merging so far. It only creates PR when branch build fails. 🎉

**Comment by stevenzeck** [comment]
https://github.com/renovatebot/renovate/issues/1853#issuecomment-434223203
