### ISSUE TITLE
Add brittany beautifier for Haskell

### ISSUE THREAD

**Issue by lassik** [Unibeautify/unibeautify#190]
**Beautifier Details**
Name: brittany
Link to project/homepage: https://github.com/lspitzner/brittany

**If this is a new beautifier, please fill out the below**
Languages Supported: Haskell
How is it run (node, terminal, etc): external program that reads from stdin and writes to stdout

I made a [repo with Unibeautify support](https://github.com/lassik/beautifier-brittany) by cloning [beautifier-template](https://github.com/Unibeautify/beautifier-template) and copy-pasting stuff from [beautifier-black](https://github.com/Unibeautify/beautifier-black) until I got a test to pass. This is my first ever Node and TypeScript code 😄  Hence I made as few changes as possible to try not to screw anything up. Would be nice if somone could go over them (it's all in one commit) to check for anything that needs to be fixed.

**Comment by stevenzeck** [comment]
This issue was moved to Unibeautify/beautifier-brittany#1
