### ISSUE TITLE
"unibeautify-" in repo names

### ISSUE THREAD

**Issue by lassik** [Unibeautify/unibeautify#191]
I recall there was an intent to rename repos like `unibeautify-cli` to just `cli`, now that they are under Unibeautify's own GitHub organization. If so, now would be a good time to finish that since the project is getting more polished at a fast pace. From grepping the GitHub API, here are all such repos:

* `unibeautify-cli`
* `unibeautify-beautifier`
* `unibeautify-options-importer`
* `unibeautify-ci-issues`

**Comment by Glavin001** [comment]
Fortunately, GitHub provides redirects for renamed projects, so this is safe to do.

- https://github.com/Unibeautify/cli
- https://github.com/Unibeautify/unibeautify-beautifier
  - Archived and not renamed
- https://github.com/Unibeautify/options-importer
- https://github.com/Unibeautify/ci-issues

Thanks @lassik !
