### ISSUE TITLE
Add asmfmt beautifier for assembly language

### ISSUE THREAD

**Issue by lassik** [Unibeautify/unibeautify#198]
**Beautifier Details**
Name: asmfmt
Link to project/homepage: https://github.com/klauspost/asmfmt
Languages Supported: assembly language
How is it run (node, terminal, etc): external program with simple stdin->stdout pipe

**Additional context**
@Glavin001, please create a `beautifier-asmfmt` repo under the Unibeautify organization. I'll submit a PR to implement it.

**Comment by stevenzeck** [comment]
This issue was moved to Unibeautify/beautifier-asmfmt#1
