### ISSUE TITLE
Autocorrect language name typos (like Git does for commands)

### ISSUE THREAD

**Issue by muuvmuuv** [Unibeautify/unibeautify#208]
**Describe the feature**

I have started working more with the Unibeautify CLI and had noticed that it is really hard to understand how it is working. I started with `unibeautify index.js -l javascript`, then I saw that I need to flag the file with `-f` and after a talk with @stevenzeck (See: [unibeautify-cli/issues/103](https://github.com/Unibeautify/unibeautify-cli/issues/103#issuecomment-433601293)) I had to letter `javascript` correctly. So the correct way was `unibeautify -f index.js -l JavaScript`. 

This is IMHO,  a little bit to difficult for the most users because not every developer knows the correct lettering of every language. I think we need to make this case intensitive. The corresponding lines are [LanguageManager.ts#L18](https://github.com/Unibeautify/unibeautify/blob/master/src/LanguageManager.ts#L18) and [LanguageManager.ts#L25](https://github.com/Unibeautify/unibeautify/blob/master/src/LanguageManager.ts#L25)

**Comment by lassik** [comment]
I agree. We haven't done a lot of work on the CLI yet. Hopefully the pace is picking up soon :)

**Comment by Glavin001** [comment]
I think your reasoning makes sense.

I would prefer to keep the name to be correct and exact. However, I also want the user experience to be better. How about for the time being we make autocorrect / recommendations to the user like `git` does? See https://stacktoheap.com/blog/2015/11/01/git-autocorrect-feature/ for example.

```bash
$ git psuh
git: 'psuh' is not a git command. See 'git --help'.

Did you mean this?
  push
```

My proposal:
- [ ] All documentation is properly cased (i.e. `JavaScript` not `javascript`)
- [ ] `.unibeautifyrc` file language keys should be properly cased
  - [ ] When provided a configuration file with incorrectly spelt languages, Unibeautify should not automatically work, however, it should try to recommend to the user what changes should be made (i.e. `javascript` ==> `JavaScript`)
- [ ] Unibeautify CLI should recommend to the user when `-l <language>` is not found, find the best match

**Comment by muuvmuuv** [comment]
@Glavin001 love that idea! 🎉

**Comment by Glavin001** [comment]
🎉 Awesome! I'm open to receiving a Pull Request to Unibeautify CLI which reports an error to the user for incorrectly spelt language names and then recommends similarly spelt languages for the user to fix.

I'm open to suggests on the message format. We can discuss in the PR.
For example:

```bash
$ unibeautify -f index.js -l javascript
Language 'javascript' is not found. Did you mean "JavaScript"?
```

**Comment by stevenzeck** [comment]
@Glavin001 are you on Slack?

**Comment by stevenzeck** [comment]
This issue was moved to Unibeautify/unibeautify-cli#115

**Comment by BrianLitwin** [comment]
![lebron](https://user-images.githubusercontent.com/26695477/47955016-1f542080-df68-11e8-93d6-b296f4aaa76f.gif)
