### ISSUE TITLE
Add functions/methods to retrieve options and beautifiers for a language

### ISSUE THREAD

**Issue by szeck87** [Unibeautify/unibeautify#21]
For the documentation, Atom Beautify, and potentially other things it would be best to centralize the logic that matches languages, beautifiers, and options all together.  The [docs scripts](https://github.com/Unibeautify/unibeautify.github.io/tree/develop/scripts/generate-docs) do a lot of this already, but should be in core Unibeautify so it can be reused.

- [x] List all loaded options (loadedOptions)
- [x] List all supported options (getOptionsSupportedForLanguage?)
- [x] List all loaded languages (getLoadedLanguages)
- [x] List all supported languages (supportedLanguages)
- [x] Get options supported by a beautifier for a language (getOptionsSupportedByBeautifierForLanguage)
- [x] Get languages for beautifier (getLanguagesForBeautifier)
- [x] Get languages supporting option (getLanguagesSupportingOption)
- [x] Get beautifiers for a language (getBeautifiersForLanguage)
- [x] Get beautifiers support for an option for a language (getBeautifiersSupportingOption)
- [x] Get language based on Atom Grammar and file extension (findLanguages)

**Comment by Glavin001** [comment]
I'll take care of this. Between the docs and Unibeautify CI and Atom-Beautify, I know there will be a lot of these common retrieval calls. The docs already have a ton of the work done, just need to move it to core, and also optimize.

**Comment by Glavin001** [comment]
Published to v0.6.0
