### ISSUE TITLE
Option 'align_assignment' is not working in VSCode with TypeScript

### ISSUE THREAD

**Issue by pirix-gh** [Unibeautify/unibeautify#217]
**Describe the bug**
Option 'align_assignment' is not working in VSCode with TypeScript

**To Reproduce**

```json
{
  "TypeScript": {
    "beautifiers": ["Prettier", "Pretty Diff"],
    "align_assignments": true,
    "arrow_parens": "always",
    "break_chained_methods": true,
    "end_with_comma": true,
    "end_with_semicolon": false,
    "indent_comments": true,
    "indent_style": "space",
    "jsx_brackets": true,
    "max_preserve_newlines": "2",
    "multiline_ternary": "never",
    "object_curly_spacing": false,
    "pragma_insert": false,
    "pragma_require": false,
    "quotes": "single",
    "space_after_anon_function": false
  }
}
```

**Expected behavior**
Should align assignments

**Error/Stack Traces**

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version: 0.7.0
 - VSCode: 1.30.2

**Additional context**

**Comment by prettydiff** [comment]
This is a defect on my end.  I need to do a better job of recognizing inline type assignments, for example:

`let a:number[] = [0]`

I already have an issue open for this: https://github.com/prettydiff/prettydiff/issues/538

I am working no the next major version of my parser.  Once I release the next major version this is the first thing I will work on.
