### ISSUE TITLE
Switch to using Jest for unit testing

### ISSUE THREAD

**Issue by Glavin001** [Unibeautify/unibeautify#22]
See https://facebook.github.io/jest/docs/en/snapshot-testing.html

**Comment by Glavin001** [comment]
@szeck87 thoughts?

**Comment by szeck87** [comment]
What are the benefits over ava?

**Comment by Glavin001** [comment]
I was thinking test snapshots and watching support.. although I think those are both supported by Ava, now that I looked 😜

**Comment by Glavin001** [comment]
I was reading more about Jest and found some interesting reads:

- https://facebook.github.io/jest/blog/2016/03/11/javascript-unit-testing-performance.html
- https://blog.kentcdodds.com/migrating-to-jest-881f75366e7e 
- https://github.com/kentcdodds/match-sorter/commit/79827247780afe8785f48834a911084d347f431d 
- https://gist.github.com/jamestalmage/a7444257d844fb627c71

Overall, I think Jest is headed in the right direction. While Ava is working well for us right now, I think Jest is building to scale and also has huge support. I'm going to migrate our existing tests to Jest and try it out. I think it will be for the better.
