### ISSUE TITLE
Promise' only refers to a type, but is being used as a value here.

### ISSUE THREAD

**Issue by Glavin001** [Unibeautify/unibeautify#30]
When using Unibeautify as a dependency:

```
ERROR in [at-loader] ./node_modules/unibeautify/dist/src/beautifier.d.ts:549:21
    TS2693: 'Promise' only refers to a type, but is being used as a value here.
```

**Comment by tdillon** [comment]
Do you have steps to reproduce this error?

**Comment by Glavin001** [comment]
I am unable to reproduce this today. I thought I was able to simply reproduce by installing Unibeautify (`npm install --save unibeautify`) and having a TypeScript project which imports it (`import Unibeautify from "unibeautify";`). However, doesn't appear to be throwing this issue today. Will post back here if I can reproduce again and include more steps next time.
