### ISSUE TITLE
Combine "Indent With Tabs" and "Indent Char"

### ISSUE THREAD

**Issue by Glavin001** [Unibeautify/unibeautify#31]
![image](https://user-images.githubusercontent.com/1885333/36572766-f1fe51d0-1813-11e8-94ad-571267838f8d.png)

**Comment by Glavin001** [comment]
Maybe `Indent Style` like EditorConfig: http://editorconfig.org/

**Comment by szeck87** [comment]
"Style" seems to be the consistent word.  https://eslint.org/docs/rules/indent#rule-details

**Comment by Glavin001** [comment]
Closed with https://github.com/Unibeautify/unibeautify/pull/33

**Comment by Glavin001** [comment]
Published to v0.8.0
