### ISSUE TITLE
Allow beautifiers to use their own config file instead of Unibeautify config

### ISSUE THREAD

**Issue by Glavin001** [Unibeautify/unibeautify#48]
**Important**: Read https://github.com/Unibeautify/vscode/issues/21#issuecomment-382419531 for why Unibeautify does not only use the beautifier's respective configuration files (i.e. `prettierrc` for Prettier, `eslintrc` for ESLint, etc).

---

Add option like `preferBeautifierConfig`.

# Example
When Unibeautify is iterating over the selected beautifiers and reaches beautifier Prettier and the beautifier's config is set to `preferBeautifierConfig=true` then Unibeautify should pass Prettier's config directly: https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath-options

---

Do you think `prefer_beautifier_config` should be enabled or disabled by default? Read explanation at https://github.com/Unibeautify/unibeautify/issues/48#issuecomment-382422749 

[![](https://api.gh-polls.com/poll/01CBCN6EQBAQ1NMH5XWXNCP847/Enabled%20by%20default)](https://api.gh-polls.com/poll/01CBCN6EQBAQ1NMH5XWXNCP847/Enabled%20by%20default/vote)
[![](https://api.gh-polls.com/poll/01CBCN6EQBAQ1NMH5XWXNCP847/Disabled%20by%20default)](https://api.gh-polls.com/poll/01CBCN6EQBAQ1NMH5XWXNCP847/Disabled%20by%20default/vote)

**Comment by Glavin001** [comment]
Related https://github.com/Unibeautify/unibeautify/issues/58

**Comment by Glavin001** [comment]
See list of beautifier's using `findFile` for configs: https://github.com/Glavin001/atom-beautify/search?l=CoffeeScript&q=findfile&type=

**Comment by szeck87** [comment]
I was looking over this for ESLint.  All I need to do there is pass projectPath into the cwd object of CLIEngine.  However, when I pass in rules (aka our options) and a cwd, it uses the instead of any config it finds.  So would need a way to conditionally pass in the rules here https://github.com/Unibeautify/beautifier-eslint/blob/master/src/index.ts#L32 based on whatever the flag ends up being here.

And would this be per beautifier or per language?

**Comment by szeck87** [comment]
> So we need to know ahead of time whether we should pass in Unibeautify's options or let ESLint find a config file?

Correct.

```     
 const cli: CLIEngine = new CLIEngine({
        fix: true,
        parserOptions: {
          ecmaVersion: 6,
        },
       // Pass either "rules" or "cwd"
        rules: options,
        cwd: filePath || projectPath || "",
      });
```

**Comment by Glavin001** [comment]
Maybe we should use

> configFile - The configuration file to use (default: null). If useEslintrc is true or not specified, this configuration will be merged with any configuration defined in .eslintrc.* files, with options in this configuration having precedence. Corresponds to -c.

Instead? See https://eslint.org/docs/developer-guide/nodejs-api#cliengine

Although maybe instead of the config file path we should use the config file's JSON itself.
See https://eslint.org/docs/developer-guide/nodejs-api#clienginegetconfigforfile

```javascript
const hasBeautifierConfig = Object.keys(beautifierConfig).length > 0;
const options = preferBeautifierConfig && hasBeautifierConfig ? beautifierConfig : unibeautifyConfig;
const cli: CLIEngine = new CLIEngine({
        fix: true,
        parserOptions: {
          ecmaVersion: 6,
        },
        rules: options,
        cwd: filePath || projectPath || "",
      });
```

**Comment by szeck87** [comment]
> Although maybe instead of the config file path we should use the config file's JSON itself.

We could, but we'd have to get the exact file path from the user instead of letting ESLint look relative to the file the user is working on.

**Comment by Glavin001** [comment]
>  The tricky thing is that the CLIEngine needs to be created first, and the options are already passed in.

Good point. I didn't realize. We may need to create a temporary / throw-away CLIEngine instance then, just to get the config. Then use it later.

---

Your code there looks good 👍 .

**Comment by Glavin001** [comment]
I was thinking about it last night: how about making `prefer_beautifier_config` default to `true`? Note it is just a preference, if the config file for the beautifier does not exist, then configuration from `.unibeautifyrc.yml` will be used.

**Comment by odahcam** [comment]
Should config files overide Unibeautify config or the opposite? 🤔

**Comment by Glavin001** [comment]
I think the beautifier specific configuration files should come first. This may be the expected default for new users of Unibeautify.

If `prefer_beautifier_config` was `false` by default and a user had a `.prettierrc` file already then they would need to configure Unibeautify manually to respect the `prettierrc` file:

```yaml
JavaScript:
  beautifiers: ["Prettier"]
  prefer_beautifier_config: true
```

or

```yaml
JavaScript:
  beautifiers: ["Prettier"]
  Prettier:
    prefer_beautifier_config: true
```

Still deciding on the config format. Maybe both will be allowed? The former being same as `prefer_beautifier_config` for all enabled beautifiers.

However, if `prefer_beautifier_config` is default set to `true` then their configuration file would simply be enabling the language and beautifier:

```yaml
JavaScript:
    beautifiers: ["Prettier"]
```

**Comment by odahcam** [comment]
> An objective of Unibeautify is to abstract and unify configuration. 

Unibeautify can't always have ALL the available configurations per beautifier, so we could fallback to the beautifier's own config. :)

That said, I think Unibeautify should use any existing configurations files (making migrations easy) and then stay on top, overiding any old configurations with it's own `.unibeautify.*` file.

**Comment by Glavin001** [comment]
I added a poll to the top of this issue.

Copied here:

[![](https://api.gh-polls.com/poll/01CBCN6EQBAQ1NMH5XWXNCP847/Enabled%20by%20default)](https://api.gh-polls.com/poll/01CBCN6EQBAQ1NMH5XWXNCP847/Enabled%20by%20default/vote)
[![](https://api.gh-polls.com/poll/01CBCN6EQBAQ1NMH5XWXNCP847/Disabled%20by%20default)](https://api.gh-polls.com/poll/01CBCN6EQBAQ1NMH5XWXNCP847/Disabled%20by%20default/vote)

**Comment by Glavin001** [comment]
I do not think `default_beautifier_config` indicative of its purpose. I think `prefer_beautifier_config` properly reflects what it will do: if there is a beautifier-specific configuration file prefer it over Unibeautify's, otherwise use Unibeautify's configuration.

**Comment by szeck87** [comment]
IMO it should be disabled by default, at least if the request to beautify is coming from an editor.  Some beautifiers, such as ESLint, will not respect a config file if we are also passing in rules.  So we need to know ahead of time whether the user wants to use a config file versus an editor's options (like Atom Beautify).  If it's enabled by default, we won't be passing in the options from the editor settings, and if the user does not have a config file it will error out saying no eslint configuration found and they won't know why.

I think we also need to figure out the best way to allow the user to define the hierarchy they want between Editor Settings, Unibeautify Config, and Beautifier Config.

**Comment by Glavin001** [comment]
> Some beautifiers, such as ESLint, will not respect a config file if we are also passing in rules. So we need to know ahead of time whether the user wants to use a config file versus an editor's options (like Atom Beautify). 

I want Unibeautify to be responsible for retrieving the ESLint config file and contents. Then when `beautify` is called, we already know if the ESLint config file exists and can pass it in as standard `rules` in this case. This will help for debugging (Unibeautify knows of internal configs) and also for the case you said above where we need the ability to choose.

>  If it's enabled by default, we won't be passing in the options from the editor settings, and if the user does not have a config file it will error out saying no eslint configuration found and they won't know why.

If the user does not have a config file, it will use Unibeautify's config. It will not error for this reason.
Similar to how the `Dependency` feature happens before `beautify` method of a beautifier is called.

See my code from https://github.com/Unibeautify/unibeautify/issues/48#issuecomment-381806763

```
// beautifierConfig = ESLint's config from .eslintrc file found by Unibeautify
// unibeautifyConfig = Standard options from .unibeautifyrc file and/or editor settings

const hasBeautifierConfig = Object.keys(beautifierConfig).length > 0;
const options =
  preferBeautifierConfig && hasBeautifierConfig
    ? beautifierConfig
    : unibeautifyConfig;
const cli: CLIEngine = new CLIEngine({
  fix: true,
  parserOptions: {
    ecmaVersion: 6
  },
  rules: options,
  cwd: filePath || projectPath || "",
});
```

> I think we also need to figure out the best way to allow the user to define the hierarchy they want between Editor Settings, Unibeautify Config, and Beautifier Config.

Agreed. I was thinking of having something like (name needs work):

```yaml
JavaScript:
  beautifier: ["ESLint"]
  config_order: ["Unibeautify", "ESLint", "Editor", "EditorConfig"]
```

Although I'm not totally happy with this approach.

**Comment by szeck87** [comment]
> I think we also need to figure out the best way to allow the user to define the hierarchy they want between Editor Settings, Unibeautify Config, and Beautifier Config.

> Agreed. I was thinking of having something like (name needs work).  Although I'm not totally happy with this approach.

Eh, maybe that's something Unibeautify should handle internally.  With the exception of `beautifiers`, if a user has an eslintrc config file then we should ignore Unibeautify config file completely for that language.  Same with the editor settings.

**Comment by Glavin001** [comment]
On second thought, I like default being disabled. Users opt into using eslintrc file. We want them to use Unibeautify instead. It would run slower to beautify with it enabled.

**Comment by Glavin001** [comment]
I just created a Pull Request: https://github.com/Unibeautify/unibeautify/pull/86

Please take a look and provide your feedback! 🎉

**Comment by odahcam** [comment]
I just find VERY frustrating when Unibeautify doesn't have an option for a Prettier config that's ruining my code. I think it's very important to always have a fallback method, because Unibeautify will always miss something from some beautifier. 

If you can solve that for me, I don't care about how to use, I just want to have full control.

**Comment by Glavin001** [comment]
I'm not sure I understand your comment. Do you mean Unibeautify's Prettier beautifier is missing support for an option which Prettier itself supports? See https://unibeautify.com/docs/beautifier-prettier.html#options for the list of currently supported options.
In this case, the expected behaviour is:
1) (Recommended) Contribute a Pull Request to https://www.npmjs.com/package/@unibeautify/beautifier-prettier (and https://www.npmjs.com/package/unibeautify if the option is new)
2) Use this upcoming feature #48 allowing you to use `.prettierrc` instead of `.unibeautifyrc` configuration file.
