### ISSUE TITLE
use unibeatify with prettydiff in my react app

### ISSUE THREAD

**Issue by MobileAppVault** [Unibeautify/unibeautify#5]
Hi,

I've tried to use unibeatify and prettydiff together in my react app.

Just imported unibeatify and beautifier-prettydiff but then I get this error:

```
import 'unibeautify';
import 'beautifier-prettydiff';
```

```
Error in ./~/sb-exec/lib/index.js
Module not found: 'child_process'
```

Thanks for your help!

**Comment by MobileAppVault** [comment]
Ok now I've found a way to use it... I've wrote my own "beautifier-prettydiff" without the atom wrapper. This will fix my issue in browser apps. 

By the way... Nice library!

**Comment by Glavin001** [comment]
Could you provide some more information? [beautifier-prettydiff](https://github.com/Unibeautify/beautifier-prettydiff) should work as Node.js standalone as well as within Atom. What did you change?

**Comment by Glavin001** [comment]
Closing stale issue.
