### ISSUE TITLE
Use consistent naming for do and don't options

### ISSUE THREAD

**Issue by szeck87** [Unibeautify/unibeautify#53]
I think it would be better if we stayed consistent with the naming and function of options in relation to whether they should do something or should not do something.  Take these options:

* indent_comments (comments **_should be_** indented)
* indent_inner_html (`<head>` and `<body>` section _**should be**_ indented)
* indent_scripts (scripts **_should be_** indented)
* unindent_chained_methods (chained methods **_should not be_** indented)
* keep_array_indentation (array indents should be ignored)

The odd ball is `unindent_chained_methods`.  This should probably be changed to `indent_chained_methods` with the default flipped from false to true.  That would preserve existing behavior an be consistent with the other options.

Thoughts?

**Comment by Glavin001** [comment]
👍 100% agree! `unindent_chained_methods` definitely should be flipped. And we should still to the conventions.

We could even make a linting rule to enforce naming conventions for the options file? Longer term idea though.

**Comment by Glavin001** [comment]
Closed by https://github.com/Unibeautify/unibeautify/pull/54
