### ISSUE TITLE
C++ support with beautifier clang-format

### ISSUE THREAD

**Issue by diegoferigo** [Unibeautify/unibeautify#55]
Any plan on supporting C++ in your CI? With [clang-format](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) the implementation should't be extremely tough.

**Comment by Glavin001** [comment]
Absolutely! Clang-format is supported by Atom-Beautify (see https://github.com/Glavin001/atom-beautify#beautifiers ) and I definitely want to port it over to Unibeautify once we are ready.

Please [sign up for the Unibeautify CI Beta](https://goo.gl/forms/AtYjxrdM4ri2dOFu1) if you are interested! Thanks!

**Comment by Glavin001** [comment]
Created repository https://github.com/Unibeautify/beautifier-clang-format . Closing this issue as any non-Unibeautify-core issues should be reported there.
