### ISSUE TITLE
google/code-prettify

### ISSUE THREAD

**Issue by quangkieu** [Unibeautify/unibeautify#60]
Just want to raise awareness about https://github.com/google/code-prettify
Thank you

**Comment by Glavin001** [comment]
Another great beautifier to add support for! Thanks for the recommendation.

@quangkieu would you be interested in contributing? See https://github.com/Unibeautify?utf8=%E2%9C%93&q=beautifier-&type=&language=typescript for the currently developed beautifiers (prefixed `beautifier-`).
I created https://github.com/Unibeautify/beautifier-code-prettify where you could submit Pull Requests 😃. Let @szeck87 or I know if you have any questions.

**Comment by Glavin001** [comment]
Closing as https://github.com/Unibeautify/beautifier-code-prettify is created. Future non-Unibeautify-core issues should go there.
