### ISSUE TITLE
Replace lodash functions with ES6 equivalents

### ISSUE THREAD

**Issue by szeck87** [Unibeautify/unibeautify#64]
We should start using ES6 over lodash when we can. Unfortunately not all of lodash's functions have a suitable alternative yet, but a good portion do.  Ideally we want as fewer dependencies so the install is as small as possible.

`_.filter(this.languages, (language: Language): boolean =>` can be replaced with something along the lines of `this.languages.filter((language: Language): boolean =>`.

`_.map`, `_.filter`, `_.reduce` all have ES6 equivalents.

https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#quick-links
https://www.sitepoint.com/lodash-features-replace-es6/

**Comment by Glavin001** [comment]
Agreed.

**Comment by Esemesek** [comment]
Hey guys, can I claim this issue? @Glavin001, @szeck87

**Comment by Glavin001** [comment]
Hi @Esemesek , absolutely! Thank you in advance for contributing!

I have not started working on this. @szeck87 have you?

**Comment by szeck87** [comment]
Nope, thank you @Esemesek for volunteering.  Let us know if you have any questions.

**Comment by szeck87** [comment]
@Esemesek I reworded my last comment, "Nope" was in response to @Glavin001 question to whether I started it.

**Comment by Glavin001** [comment]
@Esemesek : Any updates or questions? 😃

**Comment by Esemesek** [comment]
#73 So this is my PR. Generally I have some issues with code. There is so much code smells that I am unable to replace those methods without violating codeclimate check. It would be much easier if code was reformatted before any further changes. Classes that are 700+ lines of codes gave me headaches.

**Comment by Glavin001** [comment]
`src/beautifier.ts` definitely needs refactoring and splitting up. It's the oldest and biggest file. I try to make new features broken down. Pull Requests welcome for refactoring!

**Comment by Glavin001** [comment]
Published to v0.12.0
