### ISSUE TITLE
Compile error in update-languages.ts

### ISSUE THREAD

**Issue by szeck87** [Unibeautify/unibeautify#70]
I'm unable to compile the typescript files due to an error

`Type 'DocumentLoadResult' is not assignable to type 'GitHubLanguages'.
  Type 'undefined' is not assignable to type 'GitHubLanguages'.` 

on this line:  https://github.com/Unibeautify/unibeautify/blob/master/scripts/update-languages.ts#L30

**Comment by Glavin001** [comment]
``
    const githubLanguages: GitHubLanguages = yaml.safeLoad(body);
```

may need to be changed to:

```
    const githubLanguages: GitHubLanguages = yaml.safeLoad(body) as any;
```
