### ISSUE TITLE
Disable coverage when running VSCode debugger

### ISSUE THREAD

**Issue by szeck87** [Unibeautify/unibeautify#75]
Debugging Unibeautify in VSCode will not work 100% properly unless you disable code coverage while doing so.  So we want to add `--coverage false to the launch args.

`"args": ["--config", "jest.config.js", "--runInBand", "--coverage", "false"]`

> I have seen cases where adding a debugger statement triggered the debugger to stop, but not at the correct line. As a result, my standard practice is to turn coverage off during debugging, hence the "--coverage", "false" in the runtimeArgs parameter in launch.json

https://medium.com/@mtiller/debugging-with-typescript-jest-ts-jest-and-visual-studio-code-ef9ca8644132

**Comment by Glavin001** [comment]
Useful: https://code.visualstudio.com/docs/editor/variables-reference
