### ISSUE TITLE
Cannot uninstall unibeautify in vscode

### ISSUE THREAD

**Issue by williamzhao87** [Unibeautify/unibeautify#95]
I installed Unibeautify 0.4.0 on VSCode 1.23.1 x64 Windows 10 from the VSCode marketplace and it was not working properly for me.   Also, now the native VSCode html formatter is broken as well.

Afterwards, I tried to uninstall it, and it was stuck in Uninstalling state forever.

EDIT: uninstall works from the command-line (code --uninstall-extension Glavin001.unibeautify-vscode), just not the VSCode UI

**Comment by Glavin001** [comment]
> Afterwards, I tried to uninstall it, and it was stuck in Uninstalling state forever.

This sounds like a VSCode bug. I recommend you create an issue over at https://github.com/Microsoft/vscode or related.

---

> I installed Unibeautify 0.4.0 on VSCode 1.23.1 x64 Windows 10 from the VSCode marketplace and it was not working properly for me. Also, now the native VSCode html formatter is broken as well.

This issue can be reopened if you if you would like to provide more information about what was "not working properly" then we can try to help you. 😄

**Comment by Glavin001** [comment]
Please use https://github.com/Unibeautify/vscode for VSCode related Unibeautify issues.
